
version: '3.8'

services:
  backend:
    image: batyste/jeu-backendcompose:v1.0 
    ports:
      - "5000:5000"
    networks:
      - mynetwork

  frontend:
    image: batyste/jeu-frontendcompose:v1.0 
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

